name: Bug Report
description: File a bug report!
title: "(Bug): "
labels: ["bug"]
body:
- type: input
attributes:
  label: Browser Version
  description: Which browser version are you using?
  placeholder: "Example: Chromium v95"
validations:
  required: true
- type: dropdown
  attributes:
    label: "Extension or Userscript?"
    options:
      - Extension
      - Userscript
  validations:
    required: true
- type: input
